Repository NatLibFi/Annif, pull requests merged in 2019-08, with the labels that each got.

#313 Issue309 key files with labels only
  annif/corpus/convert.py
  annif/corpus/document.py
  annif/corpus/subject.py
  annif/corpus/types.py
  tests/test_corpus.py
Labels: bug

#319 Fix unsuccessful setting of readonly bash variable by using different name than UID
  docker-compose.yml
Labels: bug

#317 Pin VW, Gensim, and Scikit-learn versions
  .travis.yml
  Dockerfile
  Pipfile
  setup.py
Labels: enhancement

#306 Issue251 cli init command
  annif/cli.py
  annif/project.py
  tests/test_cli.py
Labels: enhancement

#300 Issue282 handling syntax errors in projects config
  annif/default_config.py
  annif/project.py
  tests/projects.cfg
  tests/projects_invalid.cfg
  tests/test_project.py
Labels: enhancement

#320 Turn AnnifException into an abstract base class and fix message prefix behavior
  annif/exception.py
  tests/test_exception.py
Labels: bug, enhancement

#323 Do not push docker image with dev tag to quay.io
  .drone.yml
  Dockerfile-dev
Labels: enhancement
