Repository NatLibFi/Annif, pull requests merged in 2019-06, with the labels that each got.

#280 Issue277 auto generate api documentation
  .gitignore
  Pipfile
  autopep8.sh
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/source/annif.analyzer.rst
  docs/source/annif.backend.rst
  docs/source/annif.corpus.rst
  docs/source/annif.rst
  docs/source/modules.rst
  requirements-dev.txt
  requirements.txt
Labels: documentation, enhancement

#279 Issue278 dockerize annif
  .dockerignore
  .drone.yml
  Dockerfile
  Dockerfile-data
  Dockerfile-dev
  Pipfile
  annif/nginx/nginx.conf
  docker-compose-portainer.yml
  docker-compose.yml
Labels: enhancement, question

#283 Inspect sys.argv for --projects with argparse before click
  annif/__init__.py
  annif/cli.py
  annif/project.py
  tests/projects_for_config_path_option.cfg
  tests/test_cli.py
Labels: enhancement

#285 Drop requirements files, attempt to run "setup.py install" in rtd
  .readthedocs.yml
  Pipfile
  requirements-dev.txt
  requirements.txt
Labels: enhancement

#284 Add vw_ensemble backend
  annif/backend/__init__.py
  annif/backend/backend.py
  annif/backend/ensemble.py
  annif/backend/mixins.py
  annif/backend/tfidf.py
  annif/backend/vw_base.py
  annif/backend/vw_ensemble.py
  annif/backend/vw_multi.py
  tests/test_backend_vw_ensemble.py
  tests/test_project.py
Labels: enhancement
