Repository NatLibFi/Annif, pull requests merged in 2019-12, with the labels that each got.

#365 Remove vw_ensemble backend
  annif/backend/__init__.py
  annif/backend/vw_base.py
  annif/backend/vw_ensemble.py
  annif/backend/vw_multi.py
  tests/test_backend_vw_ensemble.py
Labels: enhancement

#367 Disable build dryruns for pushes
  .drone.yml
Labels: docker, enhancement

#366 Issue343 omikuji backend
  .travis.yml
  annif/backend/__init__.py
  annif/backend/mixins.py
  annif/backend/omikuji.py
  annif/backend/tfidf.py
  annif/util.py
  setup.py
  tests/corpora/archaeology/documents.tsv
  tests/test_backend_omikuji.py
  tests/test_backend_vw_multi.py
  tests/test_util.py
Labels: enhancement

#368 Omikuji docker
  Dockerfile
Labels: docker, enhancement

#369 Fix for spurious "analyzer setting is missing" errors under WSGI
  annif/project.py
Labels: bug

#370 Support Python 3.8
  .travis.yml
  Pipfile
  setup.py
Labels: enhancement

#371 Upgrade omikuji 0.2
  .travis.yml
  Dockerfile
  annif/backend/omikuji.py
  setup.py
Labels: enhancement

#289 Issue250 support backend param option in train and learn commands
  annif/backend/backend.py
  annif/backend/dummy.py
  annif/backend/ensemble.py
  annif/backend/fasttext.py
  annif/backend/mixins.py
  annif/backend/nn_ensemble.py
  annif/backend/omikuji.py
  annif/backend/pav.py
  annif/backend/tfidf.py
  annif/backend/vw_multi.py
  annif/cli.py
  annif/project.py
  tests/projects.cfg
  tests/test_backend_fasttext.py
  tests/test_backend_nn_ensemble.py
  tests/test_backend_omikuji.py
  tests/test_backend_pav.py
  tests/test_backend_tfidf.py
  tests/test_backend_vw_multi.py
  tests/test_cli.py
Labels: enhancement

#373 Adapt the Maui backend for backend parameter overriding.
  annif/backend/maui.py
  tests/test_backend_maui.py
Labels: bug
