Repository NatLibFi/Annif, pull requests merged in 2020-05, with the labels that each got.

#407 Add encrypted secrets for pushing Docker image to quay.io from new Dr…
  .drone.yml
Labels: docker

#405 Upgrade to TensorFlow 2.2, Python 3.6+, drop Pipenv
  .dockerignore
  .travis.yml
  Dockerfile
  Pipfile
  README.md
  setup.py
Labels: enhancement

#408 Install CPU-only version of Tensorflow
  Dockerfile
  setup.py
Labels: docker, enhancement

#409 Upgrade fastText to official version 0.9.2
  annif/backend/fasttext.py
  setup.py
  tests/conftest.py
  tests/corpora/archaeology/fasttext.vec
  tests/test_backend_fasttext.py
Labels: enhancement

#410 Don't attempt to merge similar documents when creating fasttext train file
  annif/backend/fasttext.py
Labels: bug

#411 Run Travis CI fastText tests on Python 3.7 instead of 3.6
  .travis.yml
Labels: enhancement

#413 Upgrade to omikuji 0.3.x
  Dockerfile
  setup.py
Labels: enhancement

#412 Pin fasttext version to 0.9.2 and fix fasttext version in Dockerfile
  Dockerfile
  setup.py
Labels: bug

#417 Separate Annif projects from Flask current_app
  annif/backend/ensemble.py
  annif/backend/nn_ensemble.py
  annif/backend/pav.py
  annif/backend/vw_multi.py
  annif/project.py
  annif/util.py
  tests/conftest.py
  tests/test_backend_nn_ensemble.py
  tests/test_backend_pav.py
  tests/test_backend_vw_multi.py
  tests/test_project.py
Labels: enhancement
