Repository NatLibFi/Annif, pull requests merged in 2020-03, with the labels that each got.

#394 Fix click 7.1 compatibility in tests
  Pipfile
  setup.py
  tests/test_cli.py
Labels: bug

#392 evaluate samples: specify interpretation of metrics (per subject), ad…
  annif/eval.py
Labels: enhancement

#398 Fix silently failing rtd builds
  .readthedocs.yml
  docs/conf.py
  docs/requirements.txt
Labels: bug, documentation

#399 Misc rtd enhancements
  Pipfile
  README.md
  docs/conf.py
  docs/requirements.txt
Labels: documentation, enhancement

#400 Dockerfiles reorg and cleanup
  Dockerfile
  Dockerfile-data
  Dockerfile-dev
Labels: docker, enhancement

#397 Show notations in web UI results list
  annif/templates/home.html
Labels: enhancement
