Repository NatLibFi/Annif, pull requests merged in 2020-06, with the labels that each got.

#415 Show project train state and modification time
  annif/backend/backend.py
  annif/backend/dummy.py
  annif/backend/ensemble.py
  annif/backend/http.py
  annif/backend/maui.py
  annif/backend/nn_ensemble.py
  annif/backend/pav.py
  annif/cli.py
  annif/project.py
  annif/swagger/annif.yaml
  tests/conftest.py
  tests/test_backend_http.py
  tests/test_backend_maui.py
  tests/test_backend_nn_ensemble.py
  tests/test_backend_pav.py
  tests/test_cli.py
  tests/test_project.py
Labels: enhancement

#419 WEB-UI: Remove empty entry from list of projects.
  annif/templates/home.html
Labels: bug

#421 Pin SciPy to 1.4.1 as required by TensorFlow 2.2.0
  setup.py
Labels: bug

#422 Assign first retrieved project to selected variable.
  annif/templates/home.html
Labels: bug

#418 Multiprocessing in eval command
  annif/__init__.py
  annif/backend/dummy.py
  annif/backend/ensemble.py
  annif/backend/fasttext.py
  annif/backend/http.py
  annif/backend/maui.py
  annif/backend/mixins.py
  annif/backend/nn_ensemble.py
  annif/backend/omikuji.py
  annif/backend/pav.py
  annif/backend/tfidf.py
  annif/backend/vw_multi.py
  annif/cli.py
  annif/datadir.py
  annif/eval.py
  annif/project.py
  annif/registry.py
  annif/rest.py
  annif/suggestion.py
  annif/util.py
  tests/conftest.py
  tests/test_backend.py
  tests/test_backend_fasttext.py
  tests/test_backend_http.py
  tests/test_backend_maui.py
  tests/test_backend_omikuji.py
  tests/test_backend_pav.py
  tests/test_backend_tfidf.py
  tests/test_backend_vw_multi.py
  tests/test_cli.py
  tests/test_eval.py
  tests/test_project.py
  tests/test_suggestion.py
Labels: enhancement

#425 Rename variable that would otherwise shadow the builtin function map
  annif/cli.py
Labels: bug

#420 Update README.md; add Annif logo
  README.md
Labels: documentation, enhancement
