Repository NatLibFi/Annif, pull requests merged in 2020-01, with the labels that each got.

#375 Enable https in Swagger
  annif/swagger/annif.yaml
Labels: bug

#376 Implement --cached option for train command
  annif/backend/fasttext.py
  annif/backend/maui.py
  annif/backend/nn_ensemble.py
  annif/backend/omikuji.py
  annif/backend/pav.py
  annif/backend/tfidf.py
  annif/backend/vw_multi.py
  annif/cli.py
  annif/project.py
  tests/test_backend_fasttext.py
  tests/test_backend_maui.py
  tests/test_backend_nn_ensemble.py
  tests/test_backend_omikuji.py
  tests/test_backend_pav.py
  tests/test_backend_vw_multi.py
  tests/test_cli.py
Labels: enhancement

#379 Use sparse vectors in PAV backend
  annif/backend/pav.py
Labels: enhancement

#380 Rsync client
  Dockerfile-data
  Dockerfile-rsync
  docker-compose-annif.dev.finto.fi.yml
  docker-compose-api.annif.org.yml
Labels: docker

#381 Use LMDB and sparse vectors in nn_ensemble backend
  .travis.yml
  Dockerfile
  annif/backend/nn_ensemble.py
  setup.py
  tests/test_backend_nn_ensemble.py
Labels: enhancement

#382 Fix sonarqube errors
  annif/backend/backend.py
  annif/backend/dummy.py
  annif/backend/fasttext.py
  annif/backend/mixins.py
  annif/backend/nn_ensemble.py
  annif/backend/omikuji.py
  annif/backend/pav.py
  annif/backend/vw_multi.py
  annif/eval.py
  annif/templates/home.html
  tests/test_backend_nn_ensemble.py
  tests/test_backend_omikuji.py
  tests/test_backend_vw_multi.py
  tests/test_cli.py
  tests/test_exception.py
  tests/test_project.py
Labels: enhancement
