Repository NatLibFi/Annif, pull requests merged in 2021-09, with the labels that each got.

#528 Declare dateutil dependency
  setup.py
Labels: bug

#529 Update Docker baseimage to Debian Bullseye
  Dockerfile
Labels: bug, docker

#507 Issue464 language filtering in input text
  .github/workflows/python-package.yml
  annif/project.py
  annif/transform/__init__.py
  annif/transform/langfilter.py
  setup.py
  tests/conftest.py
  tests/test_transform_langfilter.py
Labels: enhancement
