Repository NatLibFi/Annif, pull requests merged in 2021-06, with the labels that each got.

#486 New SVC (support vector classification) backend using scikit-learn
  annif/backend/__init__.py
  annif/backend/svc.py
  tests/test_backend_svc.py
Labels: enhancement

#495 Show error when training MLLM on empty corpus
  annif/backend/mllm.py
  tests/test_backend_mllm.py
Labels: bug

#497 Remove execute permissions of some files
  annif/__init__.py
  annif/backend/yake.py
  annif/static/fonts/Jost-400-Book.otf
  annif/static/fonts/Jost-400-Book.ttf
  annif/static/fonts/Jost-500-Medium.otf
  annif/static/fonts/Jost-500-Medium.ttf
  tests/test_backend_pav.py
  tests/test_backend_yake.py
  tests/test_vocab.py
Labels: bug

#498 Update Dockerfile
  Dockerfile
Labels: docker, maintenance

#499 Update dependencies v0.53
  .github/workflows/python-package.yml
  annif/backend/tfidf.py
  setup.py
Labels: maintenance
