Repository NatLibFi/Annif, pull requests merged in 2021-05, with the labels that each got.

#487 Upgrade scikit-learn to 0.24.2
  setup.py
Labels: enhancement

#489 Add Codecov Action to GH workflow for uploading reports
  .codecov.yml
  .github/workflows/python-package.yml
Labels: bug, maintenance

#461 YAKE backend
  .github/workflows/python-package.yml
  README.md
  annif/backend/__init__.py
  annif/backend/maui.py
  annif/backend/yake.py
  annif/corpus/skos.py
  annif/project.py
  annif/util.py
  annif/vocab.py
  projects.cfg.dist
  setup.py
  tests/conftest.py
  tests/test_backend_stwfsa.py
  tests/test_backend_yake.py
  tests/test_vocab.py
Labels: enhancement

#491 Raise NotSupportedException for attempt to train YAKE
  annif/backend/yake.py
  tests/test_backend_yake.py
Labels: bug

#494 Add --version option to CLI
  annif/cli.py
  tests/test_cli.py
Labels: enhancement
