Repository NatLibFi/Annif, pull requests merged in 2021-03, with the labels that each got.

#471 Make sure suggestion scores are in the range 0.0-1.0
  annif/suggestion.py
  tests/test_suggestion.py
Labels: bug

#472 Cleanup suggestion tests
  tests/test_suggestion.py
Labels: enhancement

#474 GitHub actions
  .github/workflows/python-package.yml
  .travis.yml
  README.md
Labels: maintenance

#475 Allow configuration of nn ensemble learning rate
  annif/backend/nn_ensemble.py
  tests/test_backend_nn_ensemble.py
Labels: enhancement

#477 Optimize the optimize command
  annif/cli.py
Labels: bug

#468 Set Min Token Size to Two
  annif/analyzer/__init__.py
  annif/analyzer/analyzer.py
  annif/analyzer/simple.py
  annif/analyzer/snowball.py
  annif/analyzer/voikko.py
  tests/test_analyzer.py
  tests/test_backend_omikuji.py
Labels: enhancement
