Repository NatLibFi/Annif, pull requests merged in 2021-12, with the labels that each got.

#541 Remove Maui and Vowpal Wabbit multi backends
  .github/workflows/python-package.yml
  Dockerfile
  annif/backend/__init__.py
  annif/backend/maui.py
  annif/backend/vw_multi.py
  annif/cli.py
  docker-compose.yml
  projects.cfg.dist
  setup.py
  tests/projects.cfg
  tests/test_backend_maui.py
  tests/test_backend_vw_multi.py
  tests/test_cli.py
Labels: maintenance

#544 Optimize startup time using local & lazy imports (take 2)
  annif/analyzer/analyzer.py
  annif/analyzer/snowball.py
  annif/backend/__init__.py
  annif/cli.py
  tests/test_backend.py
Labels: enhancement

#548 Allow selecting installed optional dependencies in Docker build
  Dockerfile
Labels: enhancement, docker
