Repository NatLibFi/Annif, pull requests merged in 2021-08, with the labels that each got.

#496 Support for adding input-transformation operations
  annif/analyzer/__init__.py
  annif/backend/backend.py
  annif/backend/stwfsa.py
  annif/corpus/__init__.py
  annif/corpus/document.py
  annif/project.py
  annif/transform/__init__.py
  annif/transform/inputlimiter.py
  annif/transform/transform.py
  annif/util.py
  projects.cfg.dist
  tests/projects.cfg
  tests/test_backend.py
  tests/test_backend_stwfsa.py
  tests/test_backend_tfidf.py
  tests/test_corpus.py
  tests/test_project.py
  tests/test_transform.py
Labels: enhancement

#509 Warn instead of error in case of multiple subjects per doc in SVC training
  annif/backend/svc.py
  tests/conftest.py
  tests/test_backend_svc.py
Labels: enhancement, classification

#500 Implement custom MeanLayer in nn_ensemble
  annif/backend/nn_ensemble.py
Labels: enhancement

#510 Use set as container of uris instead of list in DocumentFile
  annif/corpus/document.py
  tests/test_backend_svc.py
Labels: bug

#512 Support jobs parameter in train command
  annif/backend/backend.py
  annif/backend/ensemble.py
  annif/backend/fasttext.py
  annif/backend/maui.py
  annif/backend/mllm.py
  annif/backend/nn_ensemble.py
  annif/backend/omikuji.py
  annif/backend/pav.py
  annif/backend/stwfsa.py
  annif/backend/svc.py
  annif/backend/tfidf.py
  annif/backend/vw_multi.py
  annif/backend/yake.py
  annif/cli.py
  annif/project.py
  tests/test_backend_fasttext.py
Labels: enhancement

#513 Keep serialized dump of SKOS graph to save parsing time
  annif/corpus/skos.py
  annif/vocab.py
  tests/test_cli.py
  tests/test_vocab.py
Labels: enhancement

#515 Allow NN ensemble to be used for parallel eval
  annif/backend/backend.py
  annif/backend/dummy.py
  annif/backend/ensemble.py
  annif/backend/fasttext.py
  annif/backend/mllm.py
  annif/backend/nn_ensemble.py
  annif/backend/omikuji.py
  annif/backend/pav.py
  annif/backend/stwfsa.py
  annif/backend/svc.py
  annif/backend/tfidf.py
  annif/backend/vw_multi.py
  annif/backend/yake.py
  annif/cli.py
  annif/project.py
  tests/test_backend_nn_ensemble.py
Labels: bug

#518 Use least frequent token as key in TokenSetIndex used by MLLM
  annif/lexical/mllm.py
  annif/lexical/tokenset.py
  tests/test_lexical_tokenset.py
Labels: enhancement

#519 SKOS graph cache enhancements
  annif/corpus/skos.py
  annif/vocab.py
  tests/test_cli.py
  tests/test_vocab.py
Labels: enhancement

#520 Optimize limit_mask creation
  annif/suggestion.py
Labels: enhancement

#522 Allow private projects to be accessed from CLI
  annif/cli.py
Labels: bug

#511 Process training docs in parallel in MLLM backend
  annif/backend/mllm.py
  annif/lexical/mllm.py
  annif/parallel.py
Labels: enhancement

#523 Make Drone builds start on all git tag events
  .drone.yml
Labels: bug

#525 Much faster updating of existing large vocabulary
  annif/corpus/subject.py
Labels: bug
