Repository NatLibFi/Annif, pull requests merged in 2022-01, with the labels that each got.

#550 Drop Python 3.6 support
  .github/workflows/python-package.yml
  README.md
  setup.py
Labels: maintenance

#551 Remove swagger-tester dependency
  setup.py
  tests/conftest.py
  tests/test_swagger.py
Labels: maintenance

#549 Update dependencies v0.56
  annif/backend/omikuji.py
  annif/backend/pav.py
  annif/backend/tfidf.py
  annif/eval.py
  annif/lexical/mllm.py
  annif/lexical/util.py
  annif/suggestion.py
  setup.py
Labels: enhancement, maintenance

#553 Update Scrutinizer config
  .scrutinizer.yml
Labels: maintenance

#527 Add spaCy analyzer
  .github/workflows/python-package.yml
  Dockerfile
  annif/analyzer/__init__.py
  annif/analyzer/analyzer.py
  annif/analyzer/simple.py
  annif/analyzer/snowball.py
  annif/analyzer/spacy.py
  annif/analyzer/voikko.py
  annif/backend/yake.py
  setup.py
  tests/test_analyzer.py
  tests/test_analyzer_spacy.py
  tests/test_analyzer_voikko.py
Labels: enhancement

#557 Output eval metrics as a JSON file compatible with DVC
  annif/cli.py
  annif/eval.py
  annif/util.py
  tests/test_cli.py
  tests/test_util.py
Labels: enhancement, DVC

#558 Add --metric/-m option to eval command to select metric(s)
  annif/cli.py
  annif/eval.py
  tests/test_cli.py
Labels: enhancement, DVC

#561 Set a 10 minute timeout for GitHub Actions CI jobs
  .github/workflows/python-package.yml
Labels: maintenance

#562 Add missing import of annif.eval in MLLM backend
  annif/backend/mllm.py
Labels: bug

#563 Lazy import of spaCy to avoid startup overhead
  annif/analyzer/spacy.py
  tests/test_analyzer_spacy.py
Labels: enhancement
