Repository NatLibFi/Annif, pull requests merged in 2022-11, with the labels that each got.

#642 Upgrade jQuery to version 3.6.1
  annif/static/js/jquery-3.5.1.min.js
  annif/static/js/jquery-3.5.1.min.map
  annif/static/js/jquery-3.6.1.min.js
  annif/static/js/jquery-3.6.1.min.map
  annif/templates/home.html
Labels: enhancement

#626 use Simplemma instead of pycld3 for language detection
  .github/workflows/cicd.yml
  Dockerfile
  annif/transform/langfilter.py
  pyproject.toml
  tests/test_transform_langfilter.py
Labels: enhancement

#643 Add CONTRIBUTING.md file
  CONTRIBUTING.md
  README.md
Labels: documentation

#638 add support for spawn multiprocessing mode
  annif/parallel.py
  annif/registry.py
  tests/test_cli.py
  tests/test_parallel.py
Labels: enhancement

#645 Use tailored user-agent in requests by HTTP-backend
  annif/backend/http.py
  tests/test_backend_http.py
Labels: enhancement

#648 Upgrade Bootstrap to version 5.2.2
  annif/static/css/bootstrap.min.css
  annif/static/css/bootstrap.min.css.map
  annif/static/css/style.css
  annif/static/js/bootstrap.min.js
  annif/static/js/bootstrap.min.js.map
  annif/templates/home.html
Labels: enhancement

#650 Avoid using pytest-flake8 plugin
  .github/workflows/cicd.yml
  pyproject.toml
Labels: maintenance

#649 Upgrade REST API spec to OpenAPI 3
  annif/__init__.py
  annif/openapi/annif.yaml
  annif/rest.py
  annif/swagger/annif.yaml
  annif/templates/home.html
  tests/test_rest.py
Labels: enhancement

#652 Website 2022
  www/index.html
  www/static/img/kb.png
  www/static/js/jquery-3.3.1.min.js
  www/static/js/jquery-3.3.1.min.map
  www/static/js/jquery-3.6.1.min.js
  www/static/js/jquery-3.6.1.min.map
  www/static/js/jquery.min.js
  www/static/js/jquery.min.map
Labels: enhancement

#646 Use axios in web UI
  annif/static/js/axios.min.js
  annif/static/js/axios.min.js.map
  annif/static/js/jquery-3.6.1.min.js
  annif/static/js/jquery-3.6.1.min.map
  annif/templates/home.html
Labels: enhancement
