Repository NatLibFi/Annif, pull requests merged in 2022-08, with the labels that each got.

#598 Pin flake8 to version 4.x to avoid pytest-flake8 breakage
  setup.py
Labels: bug, maintenance

#592 Add Python 3.10 support & update dependencies
  .github/workflows/cicd.yml
  README.md
  setup.py
  tests/test_cli.py
Labels: enhancement, maintenance

#597 Include labels without language tag and concepts without labels in vocabulary
  annif/corpus/skos.py
  annif/lexical/mllm.py
  tests/test_vocab_skos.py
Labels: enhancement

#600 Make vocabularies multilingual
  annif/cli.py
  annif/corpus/skos.py
  annif/corpus/subject.py
  annif/project.py
  annif/vocab.py
  tests/conftest.py
  tests/projects.cfg
  tests/test_cli.py
  tests/test_project.py
  tests/test_vocab.py
  tests/test_vocab_skos.py
Labels: enhancement

#604 Refactor SubjectSuggestion to store subject_id - not uri, label, notation
  annif/backend/backend.py
  annif/backend/dummy.py
  annif/backend/ensemble.py
  annif/backend/fasttext.py
  annif/backend/http.py
  annif/backend/mllm.py
  annif/backend/nn_ensemble.py
  annif/backend/omikuji.py
  annif/backend/pav.py
  annif/backend/stwfsa.py
  annif/backend/svc.py
  annif/backend/tfidf.py
  annif/backend/yake.py
  annif/cli.py
  annif/corpus/skos.py
  annif/corpus/subject.py
  annif/corpus/types.py
  annif/eval.py
  annif/rest.py
  annif/suggestion.py
  annif/util.py
  annif/vocab.py
  tests/conftest.py
  tests/corpora/dummy-subjects.tsv
  tests/test_backend.py
  tests/test_backend_fasttext.py
  tests/test_backend_http.py
  tests/test_backend_mllm.py
  tests/test_backend_omikuji.py
  tests/test_backend_stwfsa.py
  tests/test_backend_svc.py
  tests/test_backend_tfidf.py
  tests/test_backend_yake.py
  tests/test_cli.py
  tests/test_eval.py
  tests/test_project.py
  tests/test_rest.py
  tests/test_suggestion.py
  tests/test_vocab.py
Labels: enhancement, maintenance

#607 Remove language suffixes from vocabulary ids in example config
  projects.cfg.dist
Labels: maintenance

#606 Refactor SubjectSet and Document to store subject IDs instead of URIs and labels
  annif/backend/dummy.py
  annif/backend/ensemble.py
  annif/backend/fasttext.py
  annif/backend/mllm.py
  annif/backend/nn_ensemble.py
  annif/backend/omikuji.py
  annif/backend/pav.py
  annif/backend/stwfsa.py
  annif/backend/svc.py
  annif/backend/tfidf.py
  annif/cli.py
  annif/corpus/combine.py
  annif/corpus/document.py
  annif/corpus/subject.py
  annif/corpus/types.py
  annif/eval.py
  annif/lexical/mllm.py
  annif/parallel.py
  annif/project.py
  annif/rest.py
  tests/conftest.py
  tests/test_backend.py
  tests/test_backend_fasttext.py
  tests/test_backend_nn_ensemble.py
  tests/test_backend_omikuji.py
  tests/test_backend_pav.py
  tests/test_corpus.py
  tests/test_eval.py
  tests/test_project.py
  tests/test_transform.py
Labels: maintenance

#612 Add Annif logo to ReadTheDocs sidebar
  docs/conf.py
  docs/source/annif-RGB-white.png
Labels: enhancement, documentation

#613 Restore ability to use vocab language different from project language
  annif/cli.py
  annif/rest.py
  tests/corpora/dummy-subjects.csv
  tests/projects.cfg
  tests/test_cli.py
  tests/test_config.py
  tests/test_project.py
  tests/test_rest.py
Labels: bug

#611 Autogenerated CLI commands documentation on ReadTheDocs
  .readthedocs.yml
  annif/cli.py
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
  docs/source/commands.rst
  setup.py
Labels: enhancement, documentation
