Repository NatLibFi/Annif, pull requests merged in 2022-02, with the labels that each got.

#565 Avoid coverage 6.3 as it causes some tests to hang
  setup.py
Labels: bug

#555 Add CITATION.cff file
  CITATION.cff
  README.md
  setup.cfg
Labels: documentation

#560 Support TOML as a configuration file format alongside CFG/INI.
  annif/cli.py
  annif/config.py
  annif/default_config.py
  annif/registry.py
  setup.py
  tests/projects.toml
  tests/test_config.py
  tests/test_project.py
Labels: enhancement, DVC

#567 Add --force option to loadvoc CLI command
  annif/cli.py
  annif/vocab.py
  tests/test_vocab.py
Labels: enhancement

#568 Perform suggest operations in parallel using multiprocessing in nn_ensemble
  annif/backend/nn_ensemble.py
Labels: enhancement

#570 Use fulltext corpus in MLLM tests which is much faster
  annif/lexical/mllm.py
  annif/parallel.py
  tests/conftest.py
  tests/test_backend_mllm.py
Labels: enhancement

#573 Ensure setuptools and wheel are installed & up-to-date in CI unit tests
  .github/workflows/python-package.yml
Labels: maintenance

#574 Avoid running duplicated tests on PRs
  .github/workflows/python-package.yml
Labels: maintenance
