Repository NatLibFi/Annif, pull requests merged in 2022-09, with the labels that each got.

#618 upgrade to simplemma 0.8 and disable unnecessary cache
  annif/analyzer/simplemma.py
  setup.py
Labels: enhancement

#614 Implement load-vocab and list-vocab commands
  annif/cli.py
  annif/corpus/subject.py
  annif/project.py
  annif/registry.py
  annif/rest.py
  annif/vocab.py
  docs/source/commands.rst
  tests/conftest.py
  tests/test_cli.py
  tests/test_project.py
  tests/test_vocab.py
  tests/test_vocab_skos.py
Labels: enhancement

#619 Allow use of hyphens in vocabulary IDs
  annif/registry.py
  tests/projects.cfg
  tests/test_vocab.py
Labels: bug

#620 fix: make NN ensemble suggest operations silent
  annif/backend/nn_ensemble.py
Labels: bug

#605 Switch to Poetry for dependency management
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile
  MANIFEST.in
  README.md
  pyproject.toml
  pytest.ini
  setup.cfg
  setup.py
Labels: enhancement, maintenance

#621 Remove curl from Docker image
  Dockerfile
Labels: docker, maintenance

#622 Remove Poetry cache from Docker image
  Dockerfile
Labels: docker, maintenance

#624 Increase timeout of test and publish GH Actions jobs
  .github/workflows/cicd.yml
Labels: maintenance
