Repository NatLibFi/Annif, pull requests merged in 2022-10, with the labels that each got.

#627 Upgrade to joblib 1.2.x
  pyproject.toml
Labels: maintenance

#630 Allow overriding subject label language in CLI and REST suggest operations
  annif/cli.py
  annif/rest.py
  annif/swagger/annif.yaml
  tests/test_cli.py
  tests/test_rest.py
Labels: enhancement

#636 Better set up for docker-compose
  annif/nginx/nginx.conf
  docker-compose.yml
Labels: docker, maintenance
