Repository NatLibFi/Annif, pull requests merged in 2023-08, with the labels that each got.

#721 Suppress TensorFlow info messages to debug level
  annif/__init__.py
  tests/test_cli.py
Labels: bug

#722 Fix train state and modification time for unfinished project training
  annif/backend/backend.py
  annif/util.py
  tests/test_project.py
Labels: bug

#723 Updates for ReadTheDocs documentation
  .readthedocs.yml
  docs/conf.py
Labels: enhancement, documentation, maintenance

#725 Increase maximum startup time threshold (0.3 -> 0.4 s)
  tests/time-startup.sh
Labels: maintenance

#728 Avoid PytestUnknownMarkWarning due to "slow" marker
  pyproject.toml
Labels: bug

#729 Avoid scikit-learn UserWarning for vectorizer parameter token_pattern
  annif/backend/mixins.py
  annif/lexical/mllm.py
Labels: bug

#726 Update dependencies v1.0
  annif/backend/ensemble.py
  annif/backend/svc.py
  pyproject.toml
Labels: maintenance

#731 Upgrade Docker baseimage to Debian Bookworm
  Dockerfile
Labels: docker, maintenance

#732 Add completion command to commands list in RTD
  annif/cli.py
  docs/source/commands.rst
Labels: bug, documentation
