Repository NatLibFi/Annif, pull requests merged in 2023-02, with the labels that each got.

#663 Support for batch suggest operations for CLI commands
  annif/backend/backend.py
  annif/backend/dummy.py
  annif/backend/ensemble.py
  annif/backend/pav.py
  annif/cli.py
  annif/corpus/document.py
  annif/corpus/types.py
  annif/eval.py
  annif/parallel.py
  annif/project.py
  annif/rest.py
  tests/projects.cfg
  tests/test_backend.py
  tests/test_backend_fasttext.py
  tests/test_backend_http.py
  tests/test_backend_mllm.py
  tests/test_backend_nn_ensemble.py
  tests/test_backend_omikuji.py
  tests/test_backend_pav.py
  tests/test_backend_stwfsa.py
  tests/test_backend_svc.py
  tests/test_backend_tfidf.py
  tests/test_backend_yake.py
  tests/test_cli.py
  tests/test_config.py
  tests/test_corpus.py
  tests/test_project.py
Labels: enhancement

#668 Migrate codestyle to Black v23
  annif/backend/pav.py
  annif/backend/stwfsa.py
  annif/lexical/mllm.py
  annif/transform/inputlimiter.py
  annif/transform/langfilter.py
  pyproject.toml
  tests/test_exception.py
Labels: maintenance

#669 Batch suggest in Omikuji backend
  CONTRIBUTING.md
  annif/backend/backend.py
  annif/backend/omikuji.py
Labels: enhancement

#670 Implement batched suggest in SVC backend
  annif/backend/svc.py
Labels: enhancement

#671 Add log message indicating finishing projects initialization
  annif/__init__.py
  tests/test_backend_fasttext.py
Labels: enhancement

#673 Suppress duplicate log messages from subject module
  annif/corpus/subject.py
  annif/util.py
Labels: enhancement

#672 Fix slow CI/CD runs for Python 3.10
  .github/actions/prepare/action.yml
  .github/workflows/cicd.yml
Labels: bug, maintenance
