Repository NatLibFi/Annif, pull requests merged in 2023-05, with the labels that each got.

#700 Make stwfsapy an optional dependency
  .github/workflows/cicd.yml
  Dockerfile
  annif/backend/__init__.py
  pyproject.toml
  tests/test_backend.py
  tests/test_backend_stwfsa.py
Labels: maintenance

#701 Remove duplicated fasttext entry in optional dependencies list in Dockerfile
  Dockerfile
Labels: docker

#694 Improve outputs of project inspection CLI commands
  annif/cli.py
  annif/cli_util.py
  tests/test_cli.py
Labels: enhancement

#704 Show scores in outputs of `suggest`, `eval` and `index` with 4 decimals
  annif/cli.py
  annif/cli_util.py
  tests/test_cli.py
Labels: enhancement

#706 Test CLI startup time with CI/CD job
  .github/workflows/cicd.yml
  tests/time-startup.sh
Labels: maintenance

#707 Ensure system packages are up-to-date in Docker image
  Dockerfile
Labels: maintenance
