Repository NatLibFi/Annif, pull requests merged in 2023-04, with the labels that each got.

#681 Refactor: Represent suggestion results as sparse arrays
  annif/backend/backend.py
  annif/backend/dummy.py
  annif/backend/ensemble.py
  annif/backend/fasttext.py
  annif/backend/http.py
  annif/backend/mixins.py
  annif/backend/mllm.py
  annif/backend/nn_ensemble.py
  annif/backend/omikuji.py
  annif/backend/pav.py
  annif/backend/stwfsa.py
  annif/backend/svc.py
  annif/backend/tfidf.py
  annif/backend/yake.py
  annif/cli.py
  annif/cli_util.py
  annif/corpus/subject.py
  annif/eval.py
  annif/parallel.py
  annif/project.py
  annif/rest.py
  annif/suggestion.py
  annif/util.py
  tests/test_backend.py
  tests/test_backend_fasttext.py
  tests/test_backend_http.py
  tests/test_backend_mllm.py
  tests/test_backend_omikuji.py
  tests/test_backend_pav.py
  tests/test_backend_stwfsa.py
  tests/test_backend_svc.py
  tests/test_backend_tfidf.py
  tests/test_backend_yake.py
  tests/test_cli.py
  tests/test_eval.py
  tests/test_project.py
  tests/test_suggestion.py
Labels: enhancement

#683 Update dependencies v0.61
  pyproject.toml
Labels: maintenance

#695 Fix displaying of modification time for null value in Web UI project information
  annif/templates/home.html
Labels: bug

#693 Support for CLI command completions
  Dockerfile
  README.md
  annif/cli.py
  annif/cli_util.py
  docs/source/commands.rst
  tests/test_cli.py
Labels: enhancement
