Repository NatLibFi/Annif, pull requests merged in 2024-09, with the labels that each got.

#724 Upgrade Simplemma & limit its memory usage
  annif/analyzer/simplemma.py
  annif/simplemma_util.py
  annif/transform/langfilter.py
  pyproject.toml
  tests/test_simplemma_util.py
Labels: maintenance

#800 Sort language detection results by descending score
  annif/rest.py
  tests/test_rest.py
Labels: enhancement

#801 Add detect-language CLI command
  annif/cli.py
  annif/rest.py
  annif/simplemma_util.py
  tests/test_cli.py
  tests/test_simplemma_util.py
Labels: enhancement

#802 Add `detect-language` CLI command to commands list in RTD documentation
  docs/source/commands.rst
Labels: documentation

#793 Automatically add metadata to Hugging Face Hub repos when uploading projects
  annif/cli.py
  annif/config.py
  annif/hfh_util.py
  tests/conftest.py
  tests/test_cli.py
  tests/test_hfh_util.py
Labels: enhancement

#796 Update dependencies for v1.2 release
  .github/workflows/cicd.yml
  Dockerfile
  README.md
  annif/backend/nn_ensemble.py
  pyproject.toml
  tests/test_backend_nn_ensemble.py
  tests/test_eval.py
  tests/test_openapi.py
Labels: maintenance, dependencies

#803 Automate NLTK datapackage `punkt_tab` download
  README.md
  annif/analyzer/analyzer.py
  tests/test_analyzer.py
Labels: enhancement

#805 Upgrade Docker baseimage to Python 3.12
  Dockerfile
Labels: docker, maintenance, dependencies
