Repository NatLibFi/Annif, pull requests merged in 2025-08, with the labels that each got.

#843 Disable /learn API method by default
  annif/exception.py
  annif/openapi/annif.yaml
  annif/project.py
  annif/rest.py
  tests/projects.cfg
  tests/test_cli.py
  tests/test_config.py
  tests/test_project.py
  tests/test_rest.py
Labels: enhancement

#864 Flexible fusion part 2: core functionality
  annif/backend/backend.py
  annif/backend/dummy.py
  annif/backend/ensemble.py
  annif/backend/http.py
  annif/backend/mixins.py
  annif/backend/mllm.py
  annif/backend/omikuji.py
  annif/backend/pav.py
  annif/backend/stwfsa.py
  annif/backend/svc.py
  annif/backend/tfidf.py
  annif/backend/yake.py
  annif/cli.py
  annif/corpus/document.py
  annif/corpus/types.py
  annif/parallel.py
  annif/project.py
  annif/transform/__init__.py
  annif/transform/inputlimiter.py
  annif/transform/langfilter.py
  annif/transform/select.py
  annif/transform/transform.py
  tests/test_backend.py
  tests/test_backend_fasttext.py
  tests/test_backend_http.py
  tests/test_backend_mllm.py
  tests/test_backend_nn_ensemble.py
  tests/test_backend_omikuji.py
  tests/test_backend_pav.py
  tests/test_backend_stwfsa.py
  tests/test_backend_svc.py
  tests/test_backend_tfidf.py
  tests/test_backend_yake.py
  tests/test_corpus.py
  tests/test_project.py
  tests/test_transform.py
  tests/test_transform_langfilter.py
Labels: enhancement

#846 Support exclude/include rules for vocabulary concepts
  annif/default_config.py
  annif/project.py
  annif/vocab/__init__.py
  annif/vocab/rules.py
  annif/vocab/subject_index.py
  tests/corpora/archaeology/extract-yso-archaeology.rq
  tests/corpora/archaeology/yso-archaeology.rdf
  tests/corpora/archaeology/yso-archaeology.ttl
  tests/projects_invalid.cfg
  tests/projects_invalid2.cfg
  tests/test_project.py
  tests/test_vocab_rules.py
Labels: enhancement

#872 Add JSON fulltext corpus format
  annif/cli.py
  annif/corpus/document.py
  annif/corpus/json.py
  annif/corpus/types.py
  annif/schemas/document.json
  tests/test_cli.py
  tests/test_corpus.py
Labels: enhancement

#871 Update dependencies for 1.4 release
  pyproject.toml
  tests/test_cli.py
Labels: maintenance, dependencies

#869 Support Python 3.13
  .github/workflows/cicd.yml
  README.md
  pyproject.toml
Labels: maintenance

#877 Add annif index-file CLI command
  annif/cli.py
  annif/cli_util.py
  annif/corpus/document.py
  annif/corpus/json.py
  annif/corpus/types.py
  annif/rest.py
  annif/util.py
  docs/source/commands.rst
  tests/test_cli.py
  tests/test_corpus.py
Labels: enhancement

#887 Fix slow annif train JSONL test & avoid slow jsonschema import
  annif/corpus/json.py
  tests/test_cli.py
Labels: maintenance

#886 Support document_id in JSON(L) and CSV corpus formats & JSONL output
  annif/cli.py
  annif/corpus/document.py
  annif/corpus/json.py
  annif/corpus/types.py
  annif/schemas/document.json
  tests/test_cli.py
  tests/test_corpus.py
Labels: enhancement

#884 Upgrade to Poetry 2.0 / Resolve Poetry deprecation warnings
  .github/workflows/cicd.yml
  README.md
  pyproject.toml
Labels: maintenance

#882 Resolve `UserWarning: The parameter --verbosity...` for `annif list-*` CLI commands
  annif/cli.py
Labels: bug
