Repository NatLibFi/Annif, pull requests merged in 2025-02, with the labels that each got.

#831 Upgrade to EstNLTK 1.7.4; simplify license section in README
  README.md
  pyproject.toml
Labels: maintenance

#832 Make sure permissions of saved files adhere to umask setting
  annif/backend/nn_ensemble.py
  annif/util.py
  tests/test_backend_nn_ensemble.py
  tests/test_util.py
  tests/util.py
Labels: bug

#834 Ensure compatibility with MLLM models trained using Annif 1.2 or older
  annif/lexical/tokenset.py
Labels: bug

#833 Update dependencies for v1.3 release
  pyproject.toml
Labels: dependencies
